import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Script from 'next/script';
import { gtmScript, GTM_ID } from './lib/gtm';
import Navbar from "./(main)/components/Layout/Navbar";
import Footer from "./(main)/components/Layout/Footer";



const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <head>
          {/* Inject GTM script into <head> after hydration */}
          <Script id="gtm-script" strategy="afterInteractive" dangerouslySetInnerHTML={{ __html: gtmScript() }} />
          <meta name="robots" content="index, follow" />
        </head>
        <body className={`${inter.className}`}>
          {/* GTM <noscript> fallback for non-JS support */}
          <noscript>
            <iframe
              src={`https://www.googletagmanager.com/ns.html?id=${GTM_ID}`}
              height="0"
              width="0"
              style={{ display: 'none', visibility: 'hidden' }}
            />
          </noscript>
          <div className="flex flex-col min-h-screen">
            <Navbar />
            <main className="flex-grow">
              {children}
            </main>
            <Footer />
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
